# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 80b86c947f18d4af222970e135bcda19e47268d1995e6431f0c3692f159b97b96c061fe8656ccf8997ec9c40bd1be58b0f757f077b5db42c752504e545b52b49

test:
  secret_key_base: 95891d4e8067b73a8c826d7cde58e4aab222b2f5421b65333debd25caa952e3d4565477dbb2b8ede6c7a4bd9e3678126d16972d1ca2f49ef6342499938b67ca8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
